version: '3.8'

services:
  # Flask 服务
  chat-api:
    image: huangjingliang/chat-api:latest
    container_name: chat-api-container
    ports:
      - "5000:5000"
    environment:
      - MODEL_NAME=deepseek-llm
    restart: always
    depends_on:
      - ollama
    networks:
      - chat-ollama-network  # 自定义网络，名称更具描述性

  # Ollama 服务
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    volumes:
      - /root/.ollama:/root/.ollama  # 绑定挂载宿主机目录
    restart: always
    networks:
      - chat-ollama-network  # 使用相同的网络

# 定义网络
networks:
  chat-ollama-network:  # 具有描述性的网络名称
    driver: bridge
